-- MySQL Script generated by MySQL Workbench
-- Sun Sep 29 03:00:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_veterinaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_veterinaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_veterinaria` DEFAULT CHARACTER SET utf8 ;
USE `db_veterinaria` ;

-- -----------------------------------------------------
-- Table `db_veterinaria`.`programacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`programacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` VARCHAR(45) NOT NULL,
  `horaFin` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`veterinario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VETERINARIO_USUARIO1_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `fk_VETERINARIO_USUARIO1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `db_veterinaria`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `programacionId` INT NOT NULL DEFAULT '1',
  `veterinarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HORARIO_PROGRAMACION1_idx` (`programacionId` ASC) VISIBLE,
  INDEX `fk_HORARIO_VETERINARIO1_idx` (`veterinarioId` ASC) VISIBLE,
  CONSTRAINT `fk_HORARIO_PROGRAMACION1`
    FOREIGN KEY (`programacionId`)
    REFERENCES `db_veterinaria`.`programacion` (`id`),
  CONSTRAINT `fk_HORARIO_VETERINARIO1`
    FOREIGN KEY (`veterinarioId`)
    REFERENCES `db_veterinaria`.`veterinario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_CLIENTES_USUARIO1_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_USUARIO1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `db_veterinaria`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `peso` DOUBLE NOT NULL,
  `raza` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `clienteId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MASCOTA_CLIENTE1_idx` (`clienteId` ASC) VISIBLE,
  CONSTRAINT `fk_MASCOTA_CLIENTE1`
    FOREIGN KEY (`clienteId`)
    REFERENCES `db_veterinaria`.`cliente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`cita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mascotaId` INT NOT NULL,
  `veterinarioId` INT NOT NULL,
  `horarioId` INT NOT NULL,
  `cancelado` INT NOT NULL DEFAULT '0',
  `fechaRegistr` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CITA_VETERINARIO1_idx` (`veterinarioId` ASC) VISIBLE,
  INDEX `fk_CITA_HORARIO1_idx` (`horarioId` ASC) VISIBLE,
  INDEX `fk_CITA_MASCOTA1_idx` (`mascotaId` ASC) VISIBLE,
  CONSTRAINT `fk_CITA_HORARIO1`
    FOREIGN KEY (`horarioId`)
    REFERENCES `db_veterinaria`.`horario` (`id`),
  CONSTRAINT `fk_CITA_MASCOTA1`
    FOREIGN KEY (`mascotaId`)
    REFERENCES `db_veterinaria`.`mascota` (`id`),
  CONSTRAINT `fk_CITA_VETERINARIO1`
    FOREIGN KEY (`veterinarioId`)
    REFERENCES `db_veterinaria`.`veterinario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`historialclinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`historialclinico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `receta` VARCHAR(500) NULL DEFAULT NULL,
  `observaciones` VARCHAR(500) NULL DEFAULT NULL,
  `mascotaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HISTORIALCLINICO_MASCOTA1_idx` (`mascotaId` ASC) VISIBLE,
  CONSTRAINT `fk_HISTORIALCLINICO_MASCOTA1`
    FOREIGN KEY (`mascotaId`)
    REFERENCES `db_veterinaria`.`mascota` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
